### ISSUE TITLE
it wont work with gemini what to do

### ISSUE THREAD

**Issue by Uddhav07** [MervinPraison/PraisonAI#148]
![image](https://github.com/user-attachments/assets/62cc96bb-ae94-4624-ab9b-f07e00f1aa72)

**Comment by Uddhav07** [comment]
i even tried 

from langchain_google_genai import GoogleGenerativeAI

but langsmith unable to import like ughh

**Comment by MervinPraison** [comment]
make sure the agents.yaml looks like this

```
framework: crewai
topic: create movie script about cat in mars
roles:
  researcher:
    backstory: Skilled in finding and organizing information, with a focus on research
      efficiency.
    goal: Gather information about Mars and cats
    role: Researcher
    llm:  
      model: "google/gemini-1.5-flash-001"
    tasks:
      gather_research:
        description: Research and gather information about Mars, its environment,
          and cats, including their behavior and characteristics.
        expected_output: Document with research findings, including interesting facts
          and information.
    tools:
    - ''
```
